swagger: "2.0"
info:
  description: "SwaggerとAPI Gatewayのサンプルです。"
  version: "1.0.0"
  title: "Swagger Sample"
basePath: "/Prod"
tags:
  - name: "HelloWorld"
schemes:
  - "https"
paths:
  /hello:
    get:
      tags:
        - "HelloWorld"
      summary: "Pythonバージョン取得"
      description: "Lambdaで動いているPythonのバージョンを取得します。"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/HelloWorld"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws_proxy
definitions:
  HelloWorld:
    type: "object"
    required:
      - "python"
    properties:
      python:
        type: "string"
